# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_key', models.BooleanField(default=False)),
                ('is_auto_increment', models.BooleanField(default=False)),
                ('is_nullable', models.BooleanField(default=False)),
                ('is_reference', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectionElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draw', models.CharField(choices=[('split', 'split'), ('full', 'full'), ('hidden', 'hidden')], default='full', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('column', 'column'), ('table', 'table')], default='column', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Diagram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('collapsed', models.BooleanField(default=False)),
                ('layer_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.LayerElement')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='foreignkey',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Model'),
        ),
        migrations.AddField(
            model_name='foreignkey',
            name='source_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_column', to='viewer.Column'),
        ),
        migrations.AddField(
            model_name='foreignkey',
            name='source_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_table', to='viewer.Table'),
        ),
        migrations.AddField(
            model_name='foreignkey',
            name='target_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_column', to='viewer.Column'),
        ),
        migrations.AddField(
            model_name='foreignkey',
            name='target_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_table', to='viewer.Table'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Model'),
        ),
        migrations.AddField(
            model_name='connectionelement',
            name='diagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Diagram'),
        ),
        migrations.AddField(
            model_name='connectionelement',
            name='foreignKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ForeignKey'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Table'),
        ),
    ]
